#mv asn1crypto.SlackBuild asn1crypto.dspbuild
#mv augeas.SlackBuild augeas.dspbuild    
#mv cffi.SlackBuild cffi.dspbuild
#mv configobj.SlackBuild configobj.dspbuild
#mv cryptography.SlackBuild cryptography.dspbuild
#mv enum34.SlackBuild enum34.dspbuild
#mv idna.SlackBuild idna.dspbuild
#mv ipaddress.SlackBuild ipadress.dspbuild
#mv mock.SlackBuild mock.dspbuild
#mv ndg_httpsclient.SlackBuild ndg_httpsclient.dspbuild
#mv packaging.SlackBuild packaging.dspbuild
#mv psutil.SlackBuild psutil.dspbuild
#mv pyOpenSSL.SlackBuild pyOpenSSl.dspbuild
#mv pyasn1.SlackBuild pyasn1.dspbuild.dspbuild
#mv pycparser.SlackBuild pycparser.dspbuild
#mv pyparsing.SlackBuild pyparsing.dspbuild
#3mv pyrfc3339.SlackBuild pyrfc3339.dspbuild
#mv python-augeas.SlackBuild python-augeas.dspbuild
#3mv python-configargparse.SlackBuild python-configargparge.dspbuild
#3mv python-parsedatetime.SlackBuild python-parsedatetime.dspbuild
#mv python-requests.SlackBuild python-requests.dspbuild
#mv python2-pythondialog.SlackBuild python2-pythondialog.dspbuild
#mv pytz.SlackBuild  pytz.dspbuild
#mv werkzeug.SlackBuild qerkzeug.dspbuild
mv zope.component.SlackBuild zope.component.dspbuild
mv zope.event.SlackBuild zope.event.dspbuild
mv zope.interface.SlackBuild zope.interface.dspbuild
